<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'APC_driver' => $baseDir . '/system/cache.php',
    'Cache' => $baseDir . '/system/cache.php',
    'Cache_driver' => $baseDir . '/system/cache.php',
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'Cot' => $baseDir . '/system/Cot.php',
    'CotDB' => $baseDir . '/system/database.php',
    'Cotpl_block' => $baseDir . '/system/cotemplate.php',
    'Cotpl_data' => $baseDir . '/system/cotemplate.php',
    'Cotpl_expr' => $baseDir . '/system/cotemplate.php',
    'Cotpl_logical' => $baseDir . '/system/cotemplate.php',
    'Cotpl_loop' => $baseDir . '/system/cotemplate.php',
    'Cotpl_var' => $baseDir . '/system/cotemplate.php',
    'Db_cache_driver' => $baseDir . '/system/cache.php',
    'Dynamic_cache_driver' => $baseDir . '/system/cache.php',
    'File_cache' => $baseDir . '/system/cache.php',
    'JSMin' => $vendorDir . '/jsmin.php',
    'JSMinException' => $vendorDir . '/jsmin.php',
    'Memcache_driver' => $baseDir . '/system/cache.php',
    'MySQL_cache' => $baseDir . '/system/cache.php',
    'Page_cache' => $baseDir . '/system/cache.php',
    'Resources' => $baseDir . '/system/Resources.php',
    'Static_cache_driver' => $baseDir . '/system/cache.php',
    'Temporary_cache_driver' => $baseDir . '/system/cache.php',
    'Writeback_cache_driver' => $baseDir . '/system/cache.php',
    'XTemplate' => $baseDir . '/system/cotemplate.php',
    'Xcache_driver' => $baseDir . '/system/cache.php',
);
