<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'cot\\plugins\\' => array($baseDir . '/plugins'),
    'cot\\modules\\' => array($baseDir . '/modules'),
    'cot\\' => array($baseDir . '/system'),
    '' => array($vendorDir . ''),
);
