<?PHP
/**
 * English Language File for PassRecover Plugin
 *
 * @package Cotonti
 * @version 0.1.0
 * @author Cotonti Translators Team
 * @copyright Copyright (c) Cotonti Team 2008-2009
 * @license BSD
 */

defined('SED_CODE') or die('Wrong URL.');

/**
 * Plugin Title & Subtitle
 */

$L['plu_title'] = 'Password Recovery';

/**
 * Plugin Body
 */

$L['plu_email1'] = 'You may now reset your password using the link below:'; // New in N-0.0.2
$L['plu_email1b'] = 'Attention: if you did not request this password recovery email, for your information, requester IP is %1$s, and the request date and time is %2$s.'; // New in N-0.1.0
$L['plu_email2'] = 'Your password has been reset as you requested. Please change it as soon as possible and delete this email.
Your new password is';	// New in N-0.0.2
$L['plu_explain1'] = '1. Enter your email.';
$L['plu_explain2'] = '2. You will receive an Email with an emergency link. Click it to reset your password.'; // N-0.0.2
$L['plu_explain3'] = '3. Having confirmed twice your password reset request, you will receive random password generated by the system.'; // New in N-0.0.2
$L['plu_explain4'] = 'If you cleared email field in your profile, you will not be able to recover your password.<br />In this case please contact the webmaster by email.';
$L['plu_mailsent'] = 'Done, please check your mailbox in few minutes, and click the emergency link.<br />Then follow instructions.';
$L['plu_mailsent2'] = 'Password reset. Please check your mailbox in few minutes to gather your new password.'; // New in N-0.0.2
$L['plu_request'] = 'Request';
$L['plu_youremail'] = 'Your email: ';

?>