/* Seditio/LDU bbcodes used during conversion to HTML */

INSERT INTO `cot_bbcode` (`bbc_name`, `bbc_mode`, `bbc_pattern`, `bbc_replacement`, `bbc_container`, `bbc_enabled`, `bbc_priority`, `bbc_plug`, `bbc_postrender`) VALUES
('red', 'str', '[red]', '<span style="color:#F93737">', 1, 1, 128, '', 0),
('red', 'str', '[/red]', '</span>', 0, 1, 128, '', 0),
('white', 'str', '[white]', '<span style="color:#FFFFFF">', 1, 1, 128, '', 0),
('white', 'str', '[/white]', '</span>', 0, 1, 128, '', 0),
('green', 'str', '[green]', '<span style="color:#09DD09">', 1, 1, 128, '', 0),
('green', 'str', '[/green]', '</span>', 0, 1, 128, '', 0),
('blue', 'str', '[blue]', '<span style="color:#018BFF">', 1, 1, 128, '', 0),
('blue', 'str', '[/blue]', '</span>', 0, 1, 128, '', 0),
('orange', 'str', '[orange]', '<span style="color:#FF9900">', 1, 1, 128, '', 0),
('orange', 'str', '[/orange]', '</span>', 0, 1, 128, '', 0),
('yellow', 'str', '[yellow]', '<span style="color:#FFFF00">', 1, 1, 128, '', 0),
('yellow', 'str', '[/yellow]', '</span>', 0, 1, 128, '', 0),
('purple', 'str', '[purple]', '<span style="color:#A22ADA">', 1, 1, 128, '', 0),
('purple', 'str', '[/purple]', '</span>', 0, 1, 128, '', 0),
('black', 'str', '[black]', '<span style="color:#000000">', 1, 1, 128, '', 0),
('black', 'str', '[/black]', '</span>', 0, 1, 128, '', 0),
('grey', 'str', '[grey]', '<span style="color:#B9B9B9">', 1, 1, 128, '', 0),
('grey', 'str', '[/grey]', '</span>', 0, 1, 128, '', 0),
('pink', 'str', '[pink]', '<span style="color:#FFC0FF">', 1, 1, 128, '', 0),
('pink', 'str', '[/pink]', '</span>', 0, 1, 128, '', 0),
('sky', 'str', '[sky]', '<span style="color:#D1F4F9">', 1, 1, 128, '', 0),
('sky', 'str', '[/sky]', '</span>', 0, 1, 128, '', 0),
('sea', 'str', '[sea]', '<span style="color:#171A97">', 1, 1, 128, '', 0),
('sea', 'str', '[/sea]', '</span>', 0, 1, 128, '', 0),
('colleft', 'str', '[colleft]', '<div style="float: left;">', 1, 1, 128, '', 0),
('colleft', 'str', '[/colleft]', '</div>', 1, 1, 128, '', 0),
('colright', 'str', '[colright]', '<div style="float: right;">', 1, 1, 128, '', 0),
('colright', 'str', '[/colright]', '</div>', 1, 1, 128, '', 0),
('hr', 'str', '[hr]', '<hr />', 1, 1, 128, '', 0),
('p', 'str', '[p]', '<p>', 1, 1, 128, '', 0),
('p', 'str', '[/p]', '</p>', 0, 1, 128, '', 0),
('page', 'pcre', '\\[page=(\\d+)\\](.+?)\\[/page\\]', '<a href="page.php?id=$1">$2</a>', 1, 1, 128, '', 0),
('email', 'pcre', '\\[email\\](.+?)\\[/email\\]', '<a href="mailto:$1">$1</a>', 1, 1, 128, '', 0),
('email', 'pcre', '\\[email=(\\w[\\._\\w\\-]+@[\\w\\.\\-]+\\.[a-z]+)\\](.+?)\\[/email\\]', '<a href="mailto:$1">$2</a>', 1, 1, 128, '', 0);