CREATE TABLE `cot_users` (
  `user_id` int(11) NOT NULL auto_increment,
  `user_name` varchar(64) collate utf8_bin NOT NULL,
  `user_password` varchar(64) collate utf8_bin NOT NULL,
  `user_email` varchar(64) collate utf8_bin NOT NULL,
  `user_avatar` varchar(255) collate utf8_bin NOT NULL,
  `user_signature` varchar(255) collate utf8_bin NOT NULL,
  `user_photo` varchar(255) collate utf8_bin NOT NULL,
  `user_birthdate` int(11) NOT NULL default '0',
  `user_msn` varchar(64) collate utf8_bin NOT NULL,
  `user_icq` varchar(16) collate utf8_bin NOT NULL,
  `user_yahoo` varchar(64) collate utf8_bin NOT NULL,
  `user_aim` varchar(64) collate utf8_bin NOT NULL,
  `user_website` varchar(128) collate utf8_bin NOT NULL,
  `user_lastip` varchar(16) collate utf8_bin NOT NULL,
  `user_timezone` decimal(2,0) NOT NULL default '0',
  `user_gender` char(1) collate utf8_bin NOT NULL default 'U',
  `user_lastvisit` int(11) NOT NULL default '0',
  `user_regdate` int(11) NOT NULL default '0',
  `user_title` varchar(64) collate utf8_bin NOT NULL,
  `user_postcount` int(11) NOT NULL default '0',
  `user_pagecount` varchar(11) collate utf8_bin NOT NULL default '0',
  `user_skin` varchar(64) collate utf8_bin NOT NULL,
  `user_hidemail` tinyint(1) NOT NULL default '1',
  `user_pmnotify` tinyint(1) NOT NULL default '0',
  `user_sid` varchar(32) collate utf8_bin NOT NULL,
  `user_lostpass` varchar(32) collate utf8_bin NOT NULL,
  `user_auth` text collate utf8_bin NOT NULL,
  `user_newpm` int(11) NOT NULL default '0',
  `user_lang` varchar(2) collate utf8_bin NOT NULL,
  PRIMARY KEY  (`user_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;