CREATE TABLE `sed_auth` (
  `auth_id` mediumint(8) NOT NULL auto_increment,
  `auth_groupid` int(11) NOT NULL default '0',
  `auth_code` varchar(255) collate utf8_unicode_ci NOT NULL default '',
  `auth_option` varchar(255) collate utf8_unicode_ci NOT NULL default '',
  `auth_rights` tinyint(1) unsigned NOT NULL default '0',
  `auth_rights_lock` tinyint(1) unsigned NOT NULL default '0',
  `auth_setbyuserid` int(11) unsigned NOT NULL default '0',
  PRIMARY KEY  (`auth_id`),
  KEY `auth_groupid` (`auth_groupid`),
  KEY `auth_code` (`auth_code`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=175 ;

INSERT INTO `sed_auth` (`auth_id`, `auth_groupid`, `auth_code`, `auth_option`, `auth_rights`, `auth_rights_lock`, `auth_setbyuserid`) VALUES
(1, 1, 'admin', 'a', 0, 255, 1),
(2, 2, 'admin', 'a', 0, 255, 1),
(3, 3, 'admin', 'a', 0, 255, 1),
(4, 4, 'admin', 'a', 0, 255, 1),
(5, 5, 'admin', 'a', 255, 255, 1),
(6, 1, 'comments', 'a', 1, 254, 1),
(7, 2, 'comments', 'a', 1, 254, 1),
(8, 3, 'comments', 'a', 0, 255, 1),
(9, 4, 'comments', 'a', 3, 128, 1),
(10, 5, 'comments', 'a', 255, 255, 1),
(11, 1, 'index', 'a', 1, 254, 1),
(12, 2, 'index', 'a', 1, 254, 1),
(13, 3, 'index', 'a', 0, 255, 1),
(14, 4, 'index', 'a', 1, 128, 1),
(15, 5, 'index', 'a', 255, 255, 1),
(16, 1, 'message', 'a', 1, 255, 1),
(17, 2, 'message', 'a', 1, 255, 1),
(18, 3, 'message', 'a', 1, 255, 1),
(19, 4, 'message', 'a', 1, 255, 1),
(20, 5, 'message', 'a', 255, 255, 1),
(21, 1, 'pfs', 'a', 0, 255, 1),
(22, 2, 'pfs', 'a', 0, 255, 1),
(23, 3, 'pfs', 'a', 0, 255, 1),
(24, 4, 'pfs', 'a', 3, 128, 1),
(25, 5, 'pfs', 'a', 255, 255, 1),
(26, 1, 'pm', 'a', 0, 255, 1),
(27, 2, 'pm', 'a', 0, 255, 1),
(28, 3, 'pm', 'a', 0, 255, 1),
(29, 4, 'pm', 'a', 3, 128, 1),
(30, 5, 'pm', 'a', 255, 255, 1),
(31, 1, 'polls', 'a', 1, 254, 1),
(32, 2, 'polls', 'a', 1, 254, 1),
(33, 3, 'polls', 'a', 0, 255, 1),
(34, 4, 'polls', 'a', 3, 128, 1),
(35, 5, 'polls', 'a', 255, 255, 1),
(36, 1, 'ratings', 'a', 1, 254, 1),
(37, 2, 'ratings', 'a', 1, 254, 1),
(38, 3, 'ratings', 'a', 0, 255, 1),
(39, 4, 'ratings', 'a', 3, 128, 1),
(40, 5, 'ratings', 'a', 255, 255, 1),
(41, 1, 'users', 'a', 0, 254, 1),
(42, 2, 'users', 'a', 0, 254, 1),
(43, 3, 'users', 'a', 0, 255, 1),
(44, 4, 'users', 'a', 3, 128, 1),
(45, 5, 'users', 'a', 255, 255, 1),
(46, 1, 'forums', '1', 1, 254, 1),
(47, 2, 'forums', '1', 1, 254, 1),
(48, 3, 'forums', '1', 0, 255, 1),
(49, 4, 'forums', '1', 3, 128, 1),
(50, 5, 'forums', '1', 255, 255, 1),
(51, 1, 'forums', '2', 1, 254, 1),
(52, 2, 'forums', '2', 1, 254, 1),
(53, 3, 'forums', '2', 0, 255, 1),
(54, 4, 'forums', '2', 3, 128, 1),
(55, 5, 'forums', '2', 255, 255, 1),
(56, 1, 'page', 'articles', 5, 250, 1),
(57, 2, 'page', 'articles', 1, 254, 1),
(58, 3, 'page', 'articles', 0, 255, 1),
(59, 4, 'page', 'articles', 7, 128, 1),
(60, 5, 'page', 'articles', 255, 255, 1),
(61, 1, 'page', 'events', 5, 250, 1),
(62, 2, 'page', 'events', 1, 254, 1),
(63, 3, 'page', 'events', 0, 255, 1),
(64, 4, 'page', 'events', 7, 252, 1),
(65, 5, 'page', 'events', 255, 255, 1),
(66, 1, 'page', 'links', 5, 250, 1),
(67, 2, 'page', 'links', 1, 254, 1),
(68, 3, 'page', 'links', 0, 255, 1),
(69, 4, 'page', 'links', 7, 128, 1),
(70, 5, 'page', 'links', 255, 255, 1),
(71, 1, 'page', 'news', 5, 250, 1),
(72, 2, 'page', 'news', 1, 254, 1),
(73, 3, 'page', 'news', 0, 255, 1),
(74, 4, 'page', 'news', 7, 252, 1),
(75, 5, 'page', 'news', 255, 255, 1),
(81, 1, 'plug', 'cleaner', 0, 255, 1),
(82, 2, 'plug', 'cleaner', 0, 255, 1),
(83, 3, 'plug', 'cleaner', 0, 255, 1),
(84, 4, 'plug', 'cleaner', 1, 254, 1),
(85, 5, 'plug', 'cleaner', 255, 255, 1),
(86, 1, 'plug', 'forumstats', 1, 254, 1),
(87, 2, 'plug', 'forumstats', 1, 254, 1),
(88, 3, 'plug', 'forumstats', 0, 255, 1),
(89, 4, 'plug', 'forumstats', 1, 254, 1),
(90, 5, 'plug', 'forumstats', 255, 255, 1),
(91, 1, 'plug', 'massmovetopics', 0, 255, 1),
(92, 2, 'plug', 'massmovetopics', 0, 255, 1),
(93, 3, 'plug', 'massmovetopics', 0, 255, 1),
(94, 4, 'plug', 'massmovetopics', 0, 255, 1),
(95, 5, 'plug', 'massmovetopics', 255, 255, 1),
(101, 1, 'plug', 'search', 1, 254, 1),
(102, 2, 'plug', 'search', 1, 254, 1),
(103, 3, 'plug', 'search', 0, 255, 1),
(104, 4, 'plug', 'search', 1, 254, 1),
(105, 5, 'plug', 'search', 255, 255, 1),
(106, 1, 'plug', 'markitup', 1, 254, 1),
(107, 2, 'plug', 'markitup', 1, 254, 1),
(108, 3, 'plug', 'markitup', 0, 255, 1),
(109, 4, 'plug', 'markitup', 3, 252, 1),
(110, 5, 'plug', 'markitup', 255, 255, 1),
(111, 1, 'plug', 'whosonline', 1, 254, 1),
(112, 2, 'plug', 'whosonline', 1, 254, 1),
(113, 3, 'plug', 'whosonline', 0, 255, 1),
(114, 4, 'plug', 'whosonline', 1, 254, 1),
(115, 5, 'plug', 'whosonline', 255, 255, 1),
(116, 6, 'admin', 'a', 1, 0, 1),
(117, 6, 'comments', 'a', 131, 0, 1),
(118, 6, 'index', 'a', 131, 0, 1),
(119, 6, 'message', 'a', 131, 0, 1),
(120, 6, 'pfs', 'a', 131, 0, 1),
(121, 6, 'pm', 'a', 131, 0, 1),
(122, 6, 'polls', 'a', 131, 0, 1),
(123, 6, 'ratings', 'a', 131, 0, 1),
(124, 6, 'users', 'a', 3, 0, 1),
(125, 6, 'forums', '1', 131, 0, 1),
(126, 6, 'forums', '2', 131, 0, 1),
(127, 6, 'page', 'articles', 135, 0, 1),
(128, 6, 'page', 'events', 135, 0, 1),
(129, 6, 'page', 'links', 135, 0, 1),
(130, 6, 'page', 'news', 135, 0, 1),
(132, 6, 'plug', 'cleaner', 128, 255, 1),
(133, 6, 'plug', 'forumstats', 1, 254, 1),
(134, 6, 'plug', 'massmovetopics', 0, 255, 1),
(136, 6, 'plug', 'search', 1, 254, 1),
(137, 6, 'plug', 'markitup', 3, 252, 1),
(138, 6, 'plug', 'whosonline', 1, 254, 1),
(139, 1, 'plug', 'news', 1, 254, 1),
(140, 2, 'plug', 'news', 1, 254, 1),
(141, 3, 'plug', 'news', 0, 255, 1),
(142, 4, 'plug', 'news', 1, 254, 1),
(143, 5, 'plug', 'news', 255, 255, 1),
(144, 6, 'plug', 'news', 1, 254, 1),
(145, 1, 'plug', 'recentitems', 1, 254, 1),
(146, 2, 'plug', 'recentitems', 1, 254, 1),
(147, 3, 'plug', 'recentitems', 0, 255, 1),
(148, 4, 'plug', 'recentitems', 1, 254, 1),
(149, 5, 'plug', 'recentitems', 255, 255, 1),
(150, 6, 'plug', 'recentitems', 1, 254, 1),
(151, 1, 'plug', 'statistics', 1, 254, 1),
(152, 2, 'plug', 'statistics', 1, 254, 1),
(153, 3, 'plug', 'statistics', 0, 255, 1),
(154, 4, 'plug', 'statistics', 1, 254, 1),
(155, 5, 'plug', 'statistics', 255, 255, 1),
(156, 6, 'plug', 'statistics', 1, 254, 1),
(157, 1, 'plug', 'ipsearch', 0, 255, 1),
(158, 2, 'plug', 'ipsearch', 0, 255, 1),
(159, 3, 'plug', 'ipsearch', 0, 255, 1),
(160, 4, 'plug', 'ipsearch', 0, 255, 1),
(161, 5, 'plug', 'ipsearch', 255, 255, 1),
(162, 6, 'plug', 'ipsearch', 0, 255, 1),
(163, 1, 'plug', 'indexpolls', 1, 254, 1),
(164, 2, 'plug', 'indexpolls', 1, 254, 1),
(165, 3, 'plug', 'indexpolls', 0, 255, 1),
(166, 4, 'plug', 'indexpolls', 1, 254, 1),
(167, 5, 'plug', 'indexpolls', 255, 255, 1),
(168, 6, 'plug', 'indexpolls', 1, 254, 1),
(169, 5, 'plug', 'tags', 255, 255, 1),
(170, 6, 'plug', 'tags', 3, 124, 1),
(171, 2, 'plug', 'tags', 1, 254, 1),
(172, 3, 'plug', 'tags', 0, 255, 1),
(173, 4, 'plug', 'tags', 3, 124, 1),
(174, 1, 'plug', 'tags', 1, 254, 1),
(175, 1, 'structure', 'a', 0, 255, 1),
(176, 2, 'structure', 'a', 0, 255, 1),
(177, 3, 'structure', 'a', 0, 255, 1),
(178, 4, 'structure', 'a', 0, 255, 1),
(179, 5, 'structure', 'a', 255, 255, 1),
(180, 6, 'structure', 'a', 1, 0, 1);

CREATE TABLE `sed_banlist` (
  `banlist_id` int(11) NOT NULL auto_increment,
  `banlist_ip` varchar(15) collate utf8_unicode_ci NOT NULL default '',
  `banlist_email` varchar(64) collate utf8_unicode_ci NOT NULL default '',
  `banlist_reason` varchar(64) collate utf8_unicode_ci NOT NULL default '',
  `banlist_expire` int(11) default '0',
  PRIMARY KEY  (`banlist_id`),
  KEY `banlist_ip` (`banlist_ip`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE `sed_bbcode` (
  `bbc_id` int(11) NOT NULL auto_increment,
  `bbc_name` varchar(100) collate utf8_unicode_ci NOT NULL,
  `bbc_mode` enum('str','ereg','pcre','callback') collate utf8_unicode_ci NOT NULL default 'str',
  `bbc_pattern` varchar(255) collate utf8_unicode_ci NOT NULL,
  `bbc_replacement` text collate utf8_unicode_ci NOT NULL,
  `bbc_container` tinyint(4) NOT NULL default '1',
  `bbc_enabled` tinyint(1) NOT NULL default '1',
  `bbc_priority` tinyint(3) unsigned NOT NULL default '128',
  `bbc_plug` varchar(100) collate utf8_unicode_ci NOT NULL default '',
  `bbc_postrender` tinyint(1) NOT NULL default '0',
  PRIMARY KEY  (`bbc_id`),
  KEY `bbc_enabled` (`bbc_enabled`),
  KEY `bbc_priority` (`bbc_priority`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=65 ;

INSERT INTO `sed_bbcode` (`bbc_name`, `bbc_mode`, `bbc_pattern`, `bbc_replacement`, `bbc_container`, `bbc_enabled`, `bbc_priority`, `bbc_plug`, `bbc_postrender`) VALUES
('b', 'str', '[b]', '<strong>', 1, 1, 128, '', 0),
('b', 'str', '[/b]', '</strong>', 0, 1, 128, '', 0),
('i', 'str', '[i]', '<em>', 1, 1, 128, '', 0),
('i', 'str', '[/i]', '</em>', 1, 1, 128, '', 0),
('u', 'str', '[u]', '<span style="text-decoration:underline">', 1, 1, 128, '', 0),
('u', 'str', '[/u]', '</span>', 1, 1, 128, '', 0),
('s', 'str', '[s]', '<span style="text-decoration:line-through">', 1, 1, 128, '', 0),
('s', 'str', '[/s]', '</span>', 1, 1, 128, '', 0),
('center', 'str', '[center]', '<div style="text-align:center">', 1, 1, 128, '', 0),
('center', 'str', '[/center]', '</div>', 1, 1, 128, '', 0),
('left', 'str', '[left]', '<div style="text-align:left">', 1, 1, 128, '', 0),
('left', 'str', '[/left]', '</div>', 1, 1, 128, '', 0),
('right', 'str', '[right]', '<div style="text-align:right">', 1, 1, 128, '', 0),
('right', 'str', '[/right]', '</div>', 1, 1, 128, '', 0),
('justify', 'str', '[justify]', '<div style="text-align:justify">', 1, 1, 128, '', 0),
('justify', 'str', '[/justify]', '</div>', 1, 1, 128, '', 0),
('pre', 'str', '[pre]', '<pre>', 1, 1, 128, '', 0),
('pre', 'str', '[/pre]', '</pre>', 0, 1, 128, '', 0),
('nbsp', 'str', '[_]', '&nbsp;', 0, 1, 128, '', 0),
('email', 'callback', '\\[email=(\\w[\\._\\w\\-]+@[\\w\\.\\-]+\\.[a-z]+)\\](.+?)\\[/email\\]', 'return sed_obfuscate(''<a href="mailto:''.$input[1].''">''.$input[2].''</a>'');', 1, 1, 128, '', 0),
('quote', 'pcre', '\\[quote=(.+?)\\](.+?)\\[/quote\\]', '<blockquote><strong>$1:</strong><hr />$2</blockquote>', 1, 1, 128, '', 0),
('quote', 'pcre', '\\[quote\\](.+?)\\[/quote\\]', '<blockquote>$1</blockquote>', 1, 1, 128, '', 0),
('color', 'pcre', '\\[color=(#?\\w+)\\](.+?)\\[/color\\]', '<span style="color:$1">$2</span>', 1, 1, 128, '', 0),
('img', 'pcre', '\\[img\\]((?:http://|https://|ftp://)?[^"\\'';:\\?\\[]+\\.(?:jpg|jpeg|gif|png))\\[/img\\]', '<img src="$1" alt="" />', 1, 1, 128, '', 0),
('img', 'pcre', '\\[img=((?:http://|https://|ftp://)?[^\\]"\\'';:\\?]+\\.(?:jpg|jpeg|gif|png))\\]((?:http://|https://|ftp://)?[^\\]"\\'';:\\?]+\\.(?:jpg|jpeg|gif|png))\\[/img\\]', '<a href="$1"><img src="$2" alt="" /></a>', 1, 1, 128, '', 0),
('url', 'pcre', '\\[url=((?:http://|https://|ftp://)?[^\\s"\\'':\\[]+)\\](.+?)\\[/url\\]', '<a href="$1">$2</a>', 1, 1, 128, '', 0),
('url', 'pcre', '\\[url\\]((?:http://|https://|ftp://)?[^\\s"\\'':]+)\\[/url\\]', '<a href="$1">$1</a>', 1, 1, 128, '', 0),
('code', 'callback', '\\[code\\](.+?)\\[/code\\]', 'return ''<pre class="code">''.sed_bbcode_cdata($input[1]).''</pre>'';', 1, 1, 1, '', 0),
('more', 'str', '[more]', '<!--more-->', 1, 1, 128, '', 0),
('more', 'str', '[/more]', '&nbsp;', 1, 1, 128, '', 0),
('size', 'pcre', '\\[size=([1-2][0-9])\\](.+?)\\[/size\\]', '<span style="font-size:$1pt">$2</span>', 1, 1, 128, 'markitup', 0),
('h','pcre','\\[h([1-6])\\](.+?)\\[/h\\1\\]','<h$1>$2</h$1>',1,1,128,'',0),
('list','str','[list]','<ul>',1,1,128,'',0),
('list','str','[/list]','</ul>',1,1,128,'',0),
('ol','str','[ol]','<ol>',1,1,128,'',0),
('ol','str','[/ol]','</ol>',1,1,128,'',0),
('li','str','[li]','<li>',1,1,128,'',0),
('li','str','[/li]','</li>',1,1,128,'',0),
('li_short','pcre','\\[\\*\\](.*?)\\n','<li>$1</li>',0,1,128,'',0),
('table', 'str', '[table]', '<table>', 1, 1, 128, 'markitup', 0),
('table', 'str', '[/table]', '</table>', 1, 1, 128, 'markitup', 0),
('tr', 'str', '[tr]', '<tr>', 1, 1, 128, 'markitup', 0),
('tr', 'str', '[/tr]', '</tr>', 1, 1, 128, 'markitup', 0),
('th', 'str', '[th]', '<th>', 1, 1, 128, 'markitup', 0),
('th', 'str', '[/th]', '</th>', 1, 1, 128, 'markitup', 0),
('td', 'str', '[td]', '<td>', 1, 1, 128, 'markitup', 0),
('td', 'str', '[/td]', '</td>', 1, 1, 128, 'markitup', 0),
('hide', 'callback', '\\[hide\\](.+?)\\[/hide\\]', 'return $usr["id"] > 0 ? $input[1] : "<div class=\\"hidden\\">".$L["Hidden"]."</div>";', 1, 1, 150, 'markitup', 1),
('spoiler','pcre','\\[spoiler\\](.+?)\\[/spoiler\\]','<div style=\"margin:4px 0px 4px 0px\"><input type=\"button\" value=\"Show\" onclick=\"if(this.parentNode.getElementsByTagName(''div'')[0].style.display != '''') { this.parentNode.getElementsByTagName(''div'')[0].style.display = ''''; } else { this.parentNode.getElementsByTagName(''div'')[0].style.display = ''none''; }\" /><div style=\"display:none\" class=\"spoiler\">$1</div></div>',1,1,130,'markitup',0),
('spoiler', 'pcre', '\\[spoiler=([^\\]]+)\\](.+?)\\[/spoiler\\]', '<div style="margin:4px 0px 4px 0px"><input type="button" value="$1" onclick="if(this.parentNode.getElementsByTagName(''div'')[0].style.display != '''') { this.parentNode.getElementsByTagName(''div'')[0].style.display = ''''; } else { this.parentNode.getElementsByTagName(''div'')[0].style.display = ''none''; }" /><div style="display:none" class="spoiler">$2</div></div>', 1, 1, 130, 'markitup', 0),
('thumb', 'pcre', '\\[thumb=(.*?[^"\\'';:\\?]+\\.(?:jpg|jpeg|gif|png))\\](.*?[^"\\'';:\\?]+\\.(?:jpg|jpeg|gif|png))\\[/thumb\\]', '<a href="datas/users/$2"><img src="$1" alt="$2" /></a>', 1, 1, 128, '', 0),
('thumb', 'pcre', '\\[thumb\\](.*?[^"\\'';:\\?]+\\.(?:jpg|jpeg|gif|png))\\[/thumb\\]', '<a href="datas/users/$1"><img src="datas/thumbs/$1" /></a>', 1, 1, 128, '', 0),
('pfs', 'pcre', '\\[pfs\\](.*?[^"\\'';:\\?]+\\.(?:jpg|jpeg|gif|png|zip|rar|7z|pdf|txt))\\[/pfs\\]', '<strong><a href="datas/users/$1">$1</a></strong>', 1, 1, 128, '', 0);

CREATE TABLE `sed_cache` (
  `c_name` varchar(120) collate utf8_unicode_ci NOT NULL,
  `c_realm` varchar(80) collate utf8_unicode_ci NOT NULL default 'cot',
  `c_expire` int(11) NOT NULL default '0',
  `c_auto` tinyint(1) NOT NULL default '0',
  `c_value` text collate utf8_unicode_ci,
  PRIMARY KEY  (`c_name`, `c_realm`),
  KEY (`c_realm`),
  KEY (`c_name`),
  KEY (`c_expire`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `sed_cache_bindings` (
  `c_event` VARCHAR(80) collate utf8_unicode_ci NOT NULL,
  `c_id` VARCHAR(120) collate utf8_unicode_ci NOT NULL,
  `c_realm` VARCHAR(80) collate utf8_unicode_ci NOT NULL DEFAULT 'cot',
  PRIMARY KEY (`c_event`, `c_id`, `c_realm`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `sed_com` (
  `com_id` int(11) NOT NULL auto_increment,
  `com_code` varchar(16) collate utf8_unicode_ci NOT NULL default '',
  `com_author` varchar(100) collate utf8_unicode_ci NOT NULL,
  `com_authorid` int(11) default NULL,
  `com_authorip` varchar(15) collate utf8_unicode_ci NOT NULL default '',
  `com_text` text collate utf8_unicode_ci NOT NULL,
  `com_html` text collate utf8_unicode_ci,
  `com_date` int(11) NOT NULL default '0',
  `com_count` int(11) NOT NULL default '0',
  `com_isspecial` tinyint(1) NOT NULL default '0',
  PRIMARY KEY  (`com_id`),
  KEY `com_code` (`com_code`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE `sed_config` (
  `config_owner` varchar(24) collate utf8_unicode_ci NOT NULL default 'core',
  `config_cat` varchar(24) collate utf8_unicode_ci NOT NULL default '',
  `config_order` char(2) collate utf8_unicode_ci NOT NULL default '00',
  `config_name` varchar(32) collate utf8_unicode_ci NOT NULL default '',
  `config_type` tinyint(2) NOT NULL default '0',
  `config_value` text collate utf8_unicode_ci NOT NULL,
  `config_default` varchar(255) collate utf8_unicode_ci NOT NULL default '',
  `config_text` varchar(255) collate utf8_unicode_ci NOT NULL default ''
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `sed_config` (`config_owner`, `config_cat`, `config_order`, `config_name`, `config_type`, `config_value`, `config_default`, `config_text`) VALUES
('core', 'title', '01', 'maintitle', 1, 'Title of your site', '', ''),
('core', 'title', '02', 'subtitle', 1, 'Subtitle', '', ''),
('core', 'main', '02', 'adminemail', 1, 'admin@mysite.com', '', ''),
('core', 'main', '05', 'clustermode', 3, '0', '', ''),
('core', 'main', '03', 'hostip', 1, '999.999.999.999', '', ''),
('core', 'main', '04', 'cache', 3, '1', '', ''),
('core', 'main', '06', 'gzip', 3, '1', '', ''),
('core', 'main', '07', 'devmode', 3, '0', '', ''),
('core', 'main', '10', 'cookiedomain', 1, '', '', ''),
('core', 'main', '10', 'cookiepath', 1, '', '', ''),
('core', 'main', '10', 'cookielifetime', 2, '5184000', '', ''),
('core', 'main', '12', 'disablehitstats', 3, '0', '', ''),
('core', 'main', '13', 'disableactivitystats', 3, '0', '', ''),
('core', 'main', '14', 'disabledbstats', 3, '0', '', ''),
('core', 'main', '20', 'shieldenabled', 3, '0', '', ''),
('core', 'main', '20', 'shieldtadjust', 2, '100', '', ''),
('core', 'main', '20', 'shieldzhammer', 2, '25', '', ''),
('core', 'main', '30', 'jquery', 3, '1', '', ''),
('core', 'main', '31', 'turnajax', 3, '1', '1', ''),
('core', 'parser', '10', 'parser_custom', 3, '0', '', ''),
('core', 'parser', '10', 'parser_cache', 3, '1', '', ''),
('core', 'parser', '10', 'parser_disable', 3, '0', '', ''),
('core', 'parser', '20', 'parsebbcodeusertext', 3, '1', '', ''),
('core', 'parser', '20', 'parsebbcodecom', 3, '1', '', ''),
('core', 'parser', '20', 'parsebbcodeforums', 3, '1', '', ''),
('core', 'parser', '20', 'parsebbcodepages', 3, '1', '', ''),
('core', 'parser', '30', 'parsesmiliesusertext', 3, '0', '', ''),
('core', 'parser', '30', 'parsesmiliescom', 3, '1', '', ''),
('core', 'parser', '30', 'parsesmiliesforums', 3, '1', '', ''),
('core', 'parser', '30', 'parsesmiliespages', 3, '0', '', ''),
('core', 'time', '11', 'dateformat', 1, 'Y-m-d H:i', '', ''),
('core', 'time', '11', 'formatmonthday', 1, 'm-d', '', ''),
('core', 'time', '11', 'formatyearmonthday', 1, 'Y-m-d', '', ''),
('core', 'time', '11', 'formatmonthdayhourmin', 1, 'm-d H:i', '', ''),
('core', 'time', '11', 'servertimezone', 1, '0', '', ''),
('core', 'time', '12', 'defaulttimezone', 1, '0', '', ''),
('core', 'time', '14', 'timedout', 2, '1200', '', ''),
('core', 'skin', '02', 'forcedefaultskin', 3, '0', '', ''),
('core', 'skin', '04', 'doctypeid', 4, '4', '', ''),
('core', 'skin', '06', 'charset', 4, 'UTF-8', '', ''),
('core', 'skin', '08', 'metakeywords', 1, '', '', ''),
('core', 'skin', '08', 'separator', 1, '/', '', ''),
('core', 'skin', '15', 'disablesysinfos', 3, '0', '', ''),
('core', 'skin', '15', 'keepcrbottom', 3, '1', '', ''),
('core', 'skin', '15', 'showsqlstats', 3, '0', '', ''),
('core', 'lang', '10', 'forcedefaultlang', 3, '0', '', ''),
('core', 'menus', '10', 'topline', 0, '', '', ''),
('core', 'menus', '10', 'banner', 0, '', '', ''),
('core', 'menus', '10', 'bottomline', 0, '', '', ''),
('core', 'menus', '15', 'menu1', 0, '<ul>\n<li><a href="index.php">Home</a></li>\n<li><a href="forums.php">Forums</a></li>\n<li><a href="list.php?c=articles">Articles</a></li>\n<li><a href="plug.php?e=search">Search</a></li>\n</ul>', '', ''),
('core', 'menus', '15', 'menu2', 0, '', '', ''),
('core', 'menus', '15', 'menu3', 0, '', '', ''),
('core', 'menus', '15', 'menu4', 0, '', '', ''),
('core', 'menus', '15', 'menu5', 0, '', '', ''),
('core', 'menus', '15', 'menu6', 0, '', '', ''),
('core', 'menus', '15', 'menu7', 0, '', '', ''),
('core', 'menus', '15', 'menu8', 0, '', '', ''),
('core', 'menus', '15', 'menu9', 0, '', '', ''),
('core', 'menus', '20', 'freetext1', 0, '', '', ''),
('core', 'menus', '20', 'freetext2', 0, '', '', ''),
('core', 'menus', '20', 'freetext3', 0, '', '', ''),
('core', 'menus', '20', 'freetext4', 0, '', '', ''),
('core', 'menus', '20', 'freetext5', 0, '', '', ''),
('core', 'menus', '20', 'freetext6', 0, '', '', ''),
('core', 'menus', '20', 'freetext7', 0, '', '', ''),
('core', 'menus', '20', 'freetext8', 0, '', '', ''),
('core', 'menus', '20', 'freetext9', 0, '', '', ''),
('core', 'comments', '01', 'disable_comments', 3, '0', '', ''),
('core', 'comments', '10', 'countcomments', 3, '1', '', ''),
('core', 'forums', '01', 'disable_forums', 3, '0', '', ''),
('core', 'forums', '10', 'hideprivateforums', 3, '0', '', ''),
('core', 'forums', '10', 'hottopictrigger', 2, '20', '', ''),
('core', 'forums', '10', 'maxtopicsperpage', 2, '30', '', ''),
('core', 'forums', '12', 'antibumpforums', 3, '0', '', ''),
('core', 'forums', '12', 'mergeforumposts', 3, '1', '', ''),
('core', 'forums', '12', 'mergetimeout', 2, '0', '', ''),
('core', 'title', '03', 'title_forum_main', 1, '{FORUM}', '', ''),
('core', 'page', '01', 'disable_page', 3, '0', '', ''),
('core', 'page', '02', 'allowphp_pages', 3, '0', '', ''),
('core', 'page', '03', 'count_admin', 3, '0', '', ''),
('core', 'structure', '05', 'maxrowsperpage', 2, '15', '', ''),
('core', 'pfs', '01', 'disable_pfs', 3, '0', '', ''),
('core', 'pfs', '02', 'pfsuserfolder', 3, '0', '', ''),
('core', 'pfs', '06', 'flashupload', 3, '0', '', ''),
('core', 'pfs', '10', 'th_amode', 2, 'GD2', '', ''),
('core', 'pfs', '10', 'th_x', 2, '112', '', ''),
('core', 'pfs', '10', 'th_y', 2, '84', '', ''),
('core', 'pfs', '10', 'th_border', 2, '4', '', ''),
('core', 'pfs', '10', 'th_dimpriority', 2, 'Width', '', ''),
('core', 'pfs', '10', 'th_keepratio', 3, '1', '', ''),
('core', 'pfs', '10', 'th_jpeg_quality', 2, '85', '', ''),
('core', 'pfs', '10', 'th_colorbg', 2, '000000', '', ''),
('core', 'pfs', '10', 'th_colortext', 2, 'FFFFFF', '', ''),
('core', 'pfs', '10', 'th_textsize', 2, '1', '', ''),
('core', 'pfs', '11', 'pfs_winclose', 3, '0', '', ''),
('core', 'plug', '01', 'disable_plug', 3, '0', '', ''),
('core', 'pm', '01', 'disable_pm', 3, '0', '', ''),
('core', 'pm', '10', 'pm_maxsize', 2, '10000', '', ''),
('core', 'pm', '10', 'pm_allownotifications', 3, '1', '', ''),
('core', 'polls', '01', 'disable_polls', 3, '0', '', ''),
('core', 'ratings', '01', 'disable_ratings', 3, '0', '', ''),
('core', 'trash', '01', 'trash_prunedelay', 2, '7', '', ''),
('core', 'trash', '10', 'trash_comment', 3, '1', '', ''),
('core', 'trash', '11', 'trash_forum', 3, '1', '', ''),
('core', 'trash', '12', 'trash_page', 3, '1', '', ''),
('core', 'trash', '13', 'trash_pm', 3, '1', '', ''),
('core', 'trash', '14', 'trash_user', 3, '1', '', ''),
('core', 'users', '01', 'disablereg', 3, '0', '', ''),
('core', 'users', '03', 'disablewhosonline', 3, '0', '', ''),
('core', 'users', '05', 'maxusersperpage', 2, '50', '', ''),
('core', 'users', '07', 'regrequireadmin', 3, '0', '', ''),
('core', 'users', '10', 'regnoactivation', 3, '0', '', ''),
('core', 'users', '10', 'useremailchange', 3, '0', '', ''),
('core', 'users', '10', 'user_email_noprotection', 3, '0', '', ''),
('core', 'users', '11', 'usertextimg', 3, '0', '', ''),
('core', 'users', '12', 'av_maxsize', 2, '8000', '', ''),
('core', 'users', '12', 'av_maxx', 2, '64', '', ''),
('core', 'users', '12', 'av_maxy', 2, '64', '', ''),
('core', 'users', '12', 'usertextmax', 2, '300', '', ''),
('core', 'users', '13', 'sig_maxsize', 2, '32000', '', ''),
('core', 'users', '13', 'sig_maxx', 2, '550', '', ''),
('core', 'users', '13', 'sig_maxy', 2, '100', '', ''),
('core', 'users', '14', 'ph_maxsize', 2, '32000', '', ''),
('core', 'users', '14', 'ph_maxx', 2, '128', '', ''),
('core', 'users', '14', 'ph_maxy', 2, '128', '', ''),
('plug', 'tags', '1', 'pages', 3, '1', '', 'Enable Tags for Pages'),
('plug', 'tags', '8', 'lim_pages', 1, '0', '', 'Limit of tags in a cloud displayed for pages, 0 is unlimited'),
('plug', 'tags', '7', 'limit', 1, '0', '', 'Max. tags per items, 0 is unlimited'),
('plug', 'tags', '6', 'order', 2, 'Alphabetical', 'Alphabetical,Frequency,Random', 'Cloud output order - alphabetical, descending frequency or random'),
('plug', 'tags', '4', 'translit', 3, '0', '', 'Transliterate Tags in URLs'),
('plug', 'tags', '3', 'title', 3, '1', '', 'Capitalize first latters of keywords'),
('core', 'pfs', '05', 'pfsnomimepass', 3, '1', '', ''),
('core', 'pfs', '04', 'pfsfilecheck', 3, '1', '', ''),
('plug', 'search', '8', 'addfields', 1, '', '', 'Additional pages fields for search, separated by commas. Example "page_extra1,page_extra2,page_key"'),
('plug', 'search', '6', 'showtext_ext', 3, '1', '', 'Show text in result for extended search'),
('plug', 'search', '7', 'searchurl', 2, 'Normal', 'Normal,Single', 'Type of forum post link to use, Single uses a Single post view, while Normal uses the traditional thread/jump-to link'),
('plug', 'search', '5', 'showtext', 3, '1', '', 'Show text in result for general search'),
('plug', 'search', '4', 'maxitems_ext', 2, '100', '15,30,50,80,100,150,200,300', 'Maximum results lines for extended search'),
('plug', 'search', '1', 'maxwords', 2, '5', '3,5,8,10', 'Maximum search words'),
('plug', 'search', '2', 'maxsigns', 2, '40', '20,30,40,50,60,70,80', 'Maximum signs in query'),
('plug', 'search', '2', 'minsigns', 2, '3', '2,3,4,5', 'Min. signs in query'),
('plug', 'search', '3', 'maxitems', 2, '50', '15,30,50,80,100,150,200', 'Maximum results lines for general search'),
('core', 'page', '06', 'autovalidate', 3, '1', '', ''),
('plug', 'whosonline', '3', 'miniavatar_y', 1, '16', '', ''),
('plug', 'whosonline', '2', 'miniavatar_x', 1, '16', '', ''),
('plug', 'whosonline', '1', 'showavatars', 3, '1', '', ''),
('plug', 'markitup', '1', 'skin', 1, 'markitup', '', ' Skin of editor (plugins/markitup/skins/xxxxx)'),
('plug', 'markitup', '2', 'autorefresh', 3, '0', '', 'Enable preview auto-refresh'),
('plug', 'markitup', '3', 'chili', 3, '0', '', 'Enable Chili tags'),
('plug', 'news', '01', 'category', 1, 'news', '', 'Category code of the parent category'),
('plug', 'news', '02', 'maxpages', 2, '10', '1,2,3,4,5,6,7,8,9,10,15,20,25,30,50,100', 'Recent pages displayed'),
('plug', 'news', '03', 'syncpagination', 3, '0', '', 'Enable pagination for additional categories'),
('core', 'main', '07', 'maintenance', 3, '0', '', ''),
('plug', 'cleaner', '1', 'userprune', 2, '2', '0,1,2,3,4,5,6,7', 'Delete the user accounts not activated within * days (0 to disable).'),
('plug', 'cleaner', '2', 'logprune', 2, '15', '0,1,2,3,7,15,30,60', 'Delete the log entries older than * days (0 to disable).'),
('plug', 'cleaner', '3', 'refprune', 2, '30', '0,15,30,60,120,180,365', 'Delete the referer entries older than * days (0 to disable).'),
('plug', 'cleaner', '4', 'pmnotread', 2, '120', '0,15,30,60,120,180,365', 'Delete the private messages older than * days and not read by the recipient (0 to disable).'),
('plug', 'cleaner', '5', 'pmnotarchived', 2, '180', '0,15,30,60,120,180,365', 'Delete the private messages older than * days and not archived (0 to disable).'),
('plug', 'cleaner', '6', 'pmold', 2, '365', '0,15,30,60,120,180,365', 'ALL the private messages older than * days (0 to disable).'),
('core', 'title', '04', 'title_forum_topics', 1, '{FORUM} - {SECTION}', '', ''),
('core', 'title', '05', 'title_forum_posts', 1, '{FORUM} - {TITLE}', '', ''),
('core', 'title', '06', 'title_forum_newtopic', 1, '{FORUM} - {SECTION}', '', ''),
('core', 'title', '07', 'title_forum_editpost', 1, '{FORUM} - {SECTION}', '', ''),
('core', 'title', '08', 'title_list', 1, '{TITLE}', '', ''),
('core', 'title', '09', 'title_page', 1, '{TITLE}', '', ''),
('core', 'title', '10', 'title_pfs', 1, '{PFS}', '', ''),
('core', 'title', '11', 'title_pm_main', 1, '{PM}', '', ''),
('core', 'title', '12', 'title_pm_send', 1, '{PM}', '', ''),
('core', 'title', '13', 'title_users_main', 1, '{USERS}', '', ''),
('core', 'title', '14', 'title_users_details', 1, '{USER} : {NAME}', '', ''),
('core', 'title', '15', 'title_users_profile', 1, '{PROFILE}', '', ''),
('core', 'title', '16', 'title_users_edit', 1, '{NAME}', '', ''),
('core', 'title', '17', 'title_users_pasrec', 1, '{PASSRECOVER}', '', ''),
('core', 'title', '18', 'title_header', 1, '{MAINTITLE} - {SUBTITLE}', '', ''),
('core', 'title', '19', 'title_header_index', 1, '{MAINTITLE} - {DESCRIPTION}', '', ''),
('plug', 'indexpolls', '2', 'mode', 2, 'Recent polls', 'Recent polls,Random polls', ''),
('plug', 'indexpolls', '1', 'maxpolls', 2, '1', '0,1,2,3,4,5', ''),
('core', 'main', '07', 'maintenancereason', 1, '', '', ''),
('core', 'polls', '02', 'ip_id_polls', 2, 'ip', '', ''),
('core', 'polls', '04', 'del_dup_options', 3, '1', '', ''),
('core', 'polls', '03', 'max_options_polls', 1, '100', '', ''),
('core', 'pfs', '03', 'pfstimename', 3, '0', '', ''),
('core', 'skin', '03', 'homebreadcrumb', 3, '0', '', ''),
('plug', 'tags', '9', 'lim_forums', 1, '0', '', 'Limit of tags in a cloud displayed in forums, 0 is unlimited'),
('plug', 'tags', '2', 'forums', 3, '1', '', 'Enable Tags for Forums'),
('plug', 'tags', '9', 'lim_index', 1, '0', '', ' Limit of tags in a cloud displayed on index, 0 is unlimited'),
('plug', 'tags', '10', 'more', 3, '1', '', 'Show All Tags link in tag clouds'),
('plug', 'tags', '12', 'index', 2, 'pages', 'pages,forums,all', 'Index page tag cloud area'),
('plug', 'tags', '13', 'autocomplete', 2, '3', '0,1,2,3,4,5,6', 'Min. chars for aucomplete'),
('core', 'comments', '03', 'expand_comments', 3, '1', '', ''),
('core', 'ratings', '02', 'ratings_allowchange', 3, '0', '', ''),
('core', 'comments', '04', 'maxcommentsperpage', 2, '15', '', ''),
('core', 'comments', '05', 'commentsize', 2, '0', '', ''),
('core', 'forums', '13', 'maxpostsperpage', 2, '15', '', ''),
('core', 'structure', '05', 'maxlistsperpage', 2, '15', '', ''),
('core', 'pfs', '06', 'maxpfsperpage', 2, '15', '', ''),
('core', 'pm', '11', 'maxpmperpage', 2, '15', '', ''),
('core', 'main', '29', 'redirbkonlogin', 3, '1', '', ''),
('core', 'main', '29', 'redirbkonlogout', 3, '0', '', ''),
('core', 'version', '01', 'revision', 0, '', '', ''),
('core', 'rss', '01', 'disable_rss', 3, '0', '', 'Disable the RSS feeds'),
('core', 'rss', '02', 'rss_timetolive', 2, '30', '', 'Refresh RSS cache every N seconds'),
('core', 'rss', '03', 'rss_maxitems', 2, '40', '', 'Max. items in RSS feed'),
('core', 'rss', '04', 'rss_charset', 4, 'UTF-8', '', 'RSS charset'),
('core', 'rss', '05', 'rss_pagemaxsymbols', 1, '', '', 'Pages. Cut element description longer than N symbols'),
('core', 'rss', '06', 'rss_commentmaxsymbols', 1, '', '', 'Comments. Cut element description longer than N symbols'),
('core', 'rss', '07', 'rss_postmaxsymbols', 1, '', '', 'Posts. Cut element description longer than N symbols'),
('core', 'email', '01', 'email_type', 2, 'mail(Standart)', '', ''),
('core', 'email', '02', 'smtp_address', 2, '', '', ''),
('core', 'email', '03', 'smtp_port', 2, '25', '', ''),
('core', 'email', '04', 'smtp_login', 2, '', '', ''),
('core', 'email', '05', 'smtp_password', 2, '', '', ''),
('core', 'email', '06', 'smtp_uses_ssl', 3, '0', '', ''),
('plug', 'recentitems', '23', 'rightscan', 3, '1', '', 'Enable prescanning category rights'),
('plug', 'recentitems', '21', 'newadditional', 3, '0', '', 'Additional modules in standalone module'),
('plug', 'recentitems', '22', 'itemsperpage', 2, '10', '1,2,3,5,10,20,30,50,100,150,200,300,500', 'Elements per page in standalone module'),
('plug', 'recentitems', '17', 'recentforumstitle', 1, '', '', 'Recent forums title length limit'),
('plug', 'recentitems', '18', 'newpages', 3, '1', '', 'Recent pages in standalone module'),
('plug', 'recentitems', '19', 'newpagestext', 1, '', '', 'New pages text length limit'),
('plug', 'recentitems', '20', 'newforums', 3, '1', '', 'Recent forums in standalone module'),
('plug', 'recentitems', '16', 'maxtopics', 2, '5', '1,2,3,4,5,6,7,8,9,10,15,20,25,30', 'Recent topics in forums displayed'),
('plug', 'recentitems', '15', 'recentforums', 3, '1', '', 'Recent forums on index'),
('plug', 'recentitems', '14', 'recentpagestext', 1, '', '', 'Recent pages text length limit'),
('plug', 'recentitems', '13', 'recentpagestitle', 1, '', '', 'Recent pages title length limit'),
('plug', 'recentitems', '12', 'maxpages', 2, '5', '1,2,3,4,5,6,7,8,9,10,15,20,25,30', 'Recent pages displayed'),
('plug', 'recentitems', '11', 'recentpages', 3, '1', '', 'Recent pages on index');

CREATE TABLE `sed_core` (
  `ct_id` mediumint(8) NOT NULL auto_increment,
  `ct_code` varchar(24) collate utf8_unicode_ci NOT NULL default '',
  `ct_title` varchar(64) collate utf8_unicode_ci NOT NULL default '',
  `ct_version` varchar(16) collate utf8_unicode_ci NOT NULL default '',
  `ct_state` tinyint(1) unsigned NOT NULL default '1',
  `ct_lock` tinyint(1) unsigned NOT NULL default '0',
  PRIMARY KEY  (`ct_id`),
  KEY `ct_code` (`ct_code`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=14 ;

INSERT INTO `sed_core` (`ct_id`, `ct_code`, `ct_title`, `ct_version`, `ct_state`, `ct_lock`) VALUES
(1, 'admin', 'Administration panel', '100', 1, 1),
(2, 'comments', 'Comments', '100', 1, 0),
(3, 'forums', 'Forums', '100', 1, 0),
(4, 'index', 'Home page', '100', 1, 1),
(5, 'message', 'Messages', '100', 1, 1),
(6, 'page', 'Pages', '100', 1, 0),
(7, 'pfs', 'Personal File Space', '100', 1, 0),
(8, 'plug', 'Plugins', '100', 1, 0),
(9, 'pm', 'Private messages', '100', 1, 0),
(10, 'polls', 'Polls', '100', 1, 0),
(11, 'ratings', 'Ratings', '100', 1, 0),
(12, 'users', 'Users', '100', 1, 1),
(13, 'trash', 'Trash Can', '110', 1, 1);

CREATE TABLE `sed_extra_fields` (
  `field_location` varchar(255) collate utf8_unicode_ci NOT NULL,
  `field_name` varchar(255) collate utf8_unicode_ci NOT NULL,
  `field_type` varchar(255) collate utf8_unicode_ci NOT NULL,
  `field_html` text collate utf8_unicode_ci NOT NULL,
  `field_variants` text collate utf8_unicode_ci NOT NULL,
  `field_description` text collate utf8_unicode_ci NOT NULL,
  KEY `field_location` (`field_location`),
  KEY `field_name` (`field_name`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `sed_extra_fields` (`field_location`, `field_name`, `field_type`, `field_html`, `field_variants`, `field_description`) VALUES
('pages', 'extra1', 'input', '<input class="text" type="text" maxlength="255" size="56" />', '', ''),
('pages', 'extra2', 'input', '<input class="text" type="text" maxlength="255" size="56" />', '', ''),
('pages', 'extra3', 'input', '<input class="text" type="text" maxlength="255" size="56" />', '', ''),
('pages', 'extra4', 'input', '<input class="text" type="text" maxlength="255" size="56" />', '', ''),
('pages', 'extra5', 'input', '<input class="text" type="text" maxlength="255" size="56" />', '', ''),
('users', 'extra1', 'input', '<input class="text" type="text" maxlength="255" size="56" />', '', ''),
('users', 'extra2', 'input', '<input class="text" type="text" maxlength="255" size="56" />', '', ''),
('users', 'extra3', 'input', '<input class="text" type="text" maxlength="255" size="56" />', '', ''),
('users', 'extra4', 'input', '<input class="text" type="text" maxlength="255" size="56" />', '', ''),
('users', 'extra5', 'input', '<input class="text" type="text" maxlength="255" size="56" />', '', ''),
('users', 'extra6', 'textarea', '<textarea cols="80" rows="6" ></textarea>', '', ''),
('users', 'extra7', 'textarea', '<textarea cols="80" rows="6" ></textarea>', '', ''),
('users', 'extra8', 'textarea', '<textarea cols="80" rows="6" ></textarea>', '', ''),
('users', 'extra9', 'textarea', '<textarea cols="80" rows="6" ></textarea>', '', '');

CREATE TABLE `sed_forum_posts` (
  `fp_id` mediumint(8) unsigned NOT NULL auto_increment,
  `fp_topicid` mediumint(8) NOT NULL default '0',
  `fp_sectionid` smallint(5) NOT NULL default '0',
  `fp_posterid` int(11) NOT NULL default '-1',
  `fp_postername` varchar(100) collate utf8_unicode_ci NOT NULL,
  `fp_creation` int(11) NOT NULL default '0',
  `fp_updated` int(11) NOT NULL default '0',
  `fp_updater` varchar(100) collate utf8_unicode_ci NOT NULL DEFAULT '',
  `fp_text` text collate utf8_unicode_ci NOT NULL,
  `fp_posterip` varchar(15) collate utf8_unicode_ci NOT NULL default '',
  `fp_html` text collate utf8_unicode_ci NOT NULL,
  PRIMARY KEY  (`fp_id`),
  UNIQUE KEY `fp_topicid` (`fp_topicid`,`fp_id`),
  KEY `fp_updated` (`fp_creation`),
  KEY `fp_posterid` (`fp_posterid`),
  KEY `fp_sectionid` (`fp_sectionid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE `sed_forum_sections` (
  `fs_id` smallint(5) unsigned NOT NULL auto_increment,
  `fs_state` tinyint(1) unsigned NOT NULL default '0',
  `fs_order` smallint(5) unsigned NOT NULL default '0',
  `fs_title` varchar(128) collate utf8_unicode_ci NOT NULL default '',
  `fs_category` varchar(64) collate utf8_unicode_ci NOT NULL default '',
  `fs_desc` varchar(255) collate utf8_unicode_ci NOT NULL default '',
  `fs_icon` varchar(255) collate utf8_unicode_ci NOT NULL default '',
  `fs_lt_id` int(11) NOT NULL default '0',
  `fs_lt_title` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `fs_lt_date` int(11) NOT NULL default '0',
  `fs_lt_posterid` int(11) NOT NULL default '-1',
  `fs_lt_postername` varchar(100) collate utf8_unicode_ci NOT NULL,
  `fs_autoprune` int(11) NOT NULL default '0',
  `fs_allowusertext` tinyint(1) NOT NULL default '1',
  `fs_allowbbcodes` tinyint(1) NOT NULL default '1',
  `fs_allowsmilies` tinyint(1) NOT NULL default '1',
  `fs_allowprvtopics` tinyint(1) NOT NULL default '0',
  `fs_countposts` tinyint(1) NOT NULL default '1',
  `fs_topiccount` mediumint(8) NOT NULL default '0',
  `fs_topiccount_pruned` int(11) default '0',
  `fs_postcount` mediumint(8) NOT NULL default '0',
  `fs_postcount_pruned` int(11) default '0',
  `fs_viewcount` mediumint(8) NOT NULL default '0',
  `fs_masterid` smallint(5) unsigned NOT NULL default '0',
  `fs_mastername` varchar(128) collate utf8_unicode_ci NOT NULL,
  `fs_allowviewers` tinyint(1) NOT NULL default '1',
  `fs_allowpolls` tinyint(1) NOT NULL default '0',
  PRIMARY KEY  (`fs_id`),
  KEY `fs_order` (`fs_order`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=3 ;

INSERT INTO `sed_forum_sections` (`fs_id`, `fs_state`, `fs_order`, `fs_title`, `fs_category`, `fs_desc`, `fs_icon`, `fs_lt_id`, `fs_lt_title`, `fs_lt_date`, `fs_lt_posterid`, `fs_lt_postername`, `fs_autoprune`, `fs_allowusertext`, `fs_allowbbcodes`, `fs_allowsmilies`, `fs_allowprvtopics`, `fs_countposts`, `fs_topiccount`, `fs_topiccount_pruned`, `fs_postcount`, `fs_postcount_pruned`, `fs_viewcount`, `fs_masterid`, `fs_mastername`, `fs_allowviewers`, `fs_allowpolls`) VALUES
(1, 0, 100, 'General discussion', 'pub', 'General chat.', 'images/admin/forums.gif', 0, '', 0, 0, '', 365, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, '', 1, 0),
(2, 0, 101, 'Off-topic', 'pub', 'Various and off-topic.', 'images/admin/forums.gif', 0, '', 0, 0, '', 365, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, '', 1, 0);

CREATE TABLE `sed_forum_structure` (
  `fn_id` mediumint(8) NOT NULL auto_increment,
  `fn_path` varchar(16) collate utf8_unicode_ci NOT NULL default '',
  `fn_code` varchar(16) collate utf8_unicode_ci NOT NULL default '',
  `fn_tpl` varchar(64) collate utf8_unicode_ci NOT NULL default '',
  `fn_title` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `fn_desc` varchar(255) collate utf8_unicode_ci NOT NULL default '',
  `fn_icon` varchar(128) collate utf8_unicode_ci NOT NULL default '',
  `fn_defstate` tinyint(1) NOT NULL default '1',
  PRIMARY KEY  (`fn_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=2 ;

INSERT INTO `sed_forum_structure` (`fn_id`, `fn_path`, `fn_code`, `fn_tpl`, `fn_title`, `fn_desc`, `fn_icon`, `fn_defstate`) VALUES
(1, '1', 'pub', '', 'Public', '', '', 1);


CREATE TABLE `sed_forum_topics` (
  `ft_id` mediumint(8) unsigned NOT NULL auto_increment,
  `ft_mode` tinyint(1) unsigned NOT NULL default '0',
  `ft_state` tinyint(1) unsigned NOT NULL default '0',
  `ft_sticky` tinyint(1) unsigned NOT NULL default '0',
  `ft_tag` varchar(16) collate utf8_unicode_ci NOT NULL default '',
  `ft_sectionid` mediumint(8) NOT NULL default '0',
  `ft_title` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `ft_desc` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `ft_creationdate` int(11) NOT NULL default '0',
  `ft_updated` int(11) NOT NULL default '0',
  `ft_postcount` mediumint(8) NOT NULL default '0',
  `ft_viewcount` mediumint(8) NOT NULL default '0',
  `ft_lastposterid` int(11) NOT NULL default '-1',
  `ft_lastpostername` varchar(100) collate utf8_unicode_ci NOT NULL,
  `ft_firstposterid` int(11) NOT NULL default '-1',
  `ft_firstpostername` varchar(100) collate utf8_unicode_ci NOT NULL,
  `ft_poll` int(11) default '0',
  `ft_movedto` int(11) default '0',
  `ft_preview` varchar(128) collate utf8_unicode_ci NOT NULL default '',
  PRIMARY KEY  (`ft_id`),
  KEY `ft_updated` (`ft_updated`),
  KEY `ft_mode` (`ft_mode`),
  KEY `ft_state` (`ft_state`),
  KEY `ft_sticky` (`ft_sticky`),
  KEY `ft_sectionid` (`ft_sectionid`),
  KEY `ft_movedto` (`ft_movedto`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE `sed_groups` (
  `grp_id` int(11) NOT NULL auto_increment,
  `grp_alias` varchar(24) collate utf8_unicode_ci NOT NULL default '',
  `grp_level` tinyint(2) NOT NULL default '1',
  `grp_disabled` tinyint(1) NOT NULL default '0',
  `grp_hidden` tinyint(1) NOT NULL default '0',
  `grp_title` varchar(64) collate utf8_unicode_ci NOT NULL default '',
  `grp_desc` varchar(255) collate utf8_unicode_ci NOT NULL default '',
  `grp_icon` varchar(128) collate utf8_unicode_ci NOT NULL default '',
  `grp_pfs_maxfile` int(11) NOT NULL default '0',
  `grp_pfs_maxtotal` int(11) NOT NULL default '0',
  `grp_ownerid` int(11) NOT NULL default '0',
  `grp_maintenance` tinyint(1) NOT NULL default '0',
  PRIMARY KEY  (`grp_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=7 ;


INSERT INTO `sed_groups` (`grp_id`, `grp_alias`, `grp_level`, `grp_disabled`, `grp_hidden`, `grp_title`, `grp_desc`, `grp_icon`, `grp_pfs_maxfile`, `grp_pfs_maxtotal`, `grp_ownerid`, `grp_maintenance`) VALUES
(1, 'guests', 0, 0, 0, 'Guests', '', '', 0, 0, 1, 0),
(2, 'inactive', 1, 0, 0, 'Inactive', '', '', 0, 0, 1, 0),
(3, 'banned', 1, 0, 0, 'Banned', '', '', 0, 0, 1, 0),
(4, 'members', 1, 0, 0, 'Members', '', '', 0, 0, 1, 0),
(5, 'administrators', 99, 0, 0, 'Administrators', '', '', 256, 1024, 1, 1),
(6, 'moderators', 50, 0, 0, 'Moderators', '', '', 256, 1024, 1, 1);

CREATE TABLE `sed_groups_users` (
  `gru_userid` int(11) NOT NULL default '0',
  `gru_groupid` int(11) NOT NULL default '0',
  `gru_state` tinyint(1) NOT NULL default '0',
  `gru_extra1` varchar(255) collate utf8_unicode_ci NOT NULL default '',
  `gru_extra2` varchar(255) collate utf8_unicode_ci NOT NULL default '',
  UNIQUE KEY `gru_groupid` (`gru_groupid`,`gru_userid`),
  KEY `gru_userid` (`gru_userid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


CREATE TABLE `sed_logger` (
  `log_id` mediumint(11) NOT NULL auto_increment,
  `log_date` int(11) NOT NULL default '0',
  `log_ip` varchar(15) collate utf8_unicode_ci NOT NULL default '',
  `log_name` varchar(100) collate utf8_unicode_ci NOT NULL,
  `log_group` varchar(4) collate utf8_unicode_ci NOT NULL default 'def',
  `log_text` varchar(255) collate utf8_unicode_ci NOT NULL default '',
  PRIMARY KEY  (`log_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE `sed_online` (
  `online_id` int(11) NOT NULL auto_increment,
  `online_ip` varchar(15) collate utf8_unicode_ci NOT NULL default '',
  `online_name` varchar(100) collate utf8_unicode_ci NOT NULL,
  `online_lastseen` int(11) NOT NULL default '0',
  `online_location` varchar(32) collate utf8_unicode_ci NOT NULL default '',
  `online_subloc` varchar(255) collate utf8_unicode_ci NOT NULL default '',
  `online_userid` int(11) NOT NULL default '0',
  `online_shield` int(11) NOT NULL default '0',
  `online_action` varchar(32) collate utf8_unicode_ci NOT NULL default '',
  `online_hammer` tinyint(1) NOT NULL default '0',
  PRIMARY KEY  (`online_id`),
  KEY `online_lastseen` (`online_lastseen`),
  KEY `online_userid` (`online_userid`),
  KEY `online_name` (`online_name`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE `sed_pages` (
  `page_id` int(11) unsigned NOT NULL auto_increment,
  `page_state` tinyint(1) unsigned NOT NULL default '0',
  `page_type` tinyint(1) default '0',
  `page_cat` varchar(255) collate utf8_unicode_ci default NULL,
  `page_key` varchar(16) collate utf8_unicode_ci default NULL,
  `page_extra1` varchar(255) collate utf8_unicode_ci NOT NULL default '',
  `page_extra2` varchar(255) collate utf8_unicode_ci NOT NULL default '',
  `page_extra3` varchar(255) collate utf8_unicode_ci NOT NULL default '',
  `page_extra4` varchar(255) collate utf8_unicode_ci NOT NULL default '',
  `page_extra5` varchar(255) collate utf8_unicode_ci NOT NULL default '',
  `page_title` varchar(255) collate utf8_unicode_ci default NULL,
  `page_desc` varchar(255) collate utf8_unicode_ci default NULL,
  `page_text` MEDIUMTEXT collate utf8_unicode_ci,
  `page_author` varchar(100) collate utf8_unicode_ci NOT NULL,
  `page_ownerid` int(11) NOT NULL default '0',
  `page_date` int(11) NOT NULL default '0',
  `page_begin` int(11) NOT NULL default '0',
  `page_expire` int(11) NOT NULL default '0',
  `page_file` tinyint(4) default NULL,
  `page_url` varchar(255) collate utf8_unicode_ci default NULL,
  `page_size` varchar(16) collate utf8_unicode_ci default NULL,
  `page_count` mediumint(8) unsigned default '0',
  `page_rating` decimal(5,2) NOT NULL default '0.00',
  `page_comcount` mediumint(8) unsigned default '0',
  `page_filecount` mediumint(8) unsigned default '0',
  `page_alias` varchar(255) collate utf8_unicode_ci NOT NULL default '',
  `page_html` MEDIUMTEXT collate utf8_unicode_ci NOT NULL,
  PRIMARY KEY  (`page_id`),
  KEY `page_cat` (`page_cat`),
  KEY `page_alias` (`page_alias`),
  KEY `page_state` (`page_state`),
  KEY `page_date` (`page_date`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=2 ;

INSERT INTO `sed_pages` (`page_id`, `page_state`, `page_type`, `page_cat`, `page_key`, `page_extra1`, `page_extra2`, `page_extra3`, `page_extra4`, `page_extra5`, `page_title`, `page_desc`, `page_text`, `page_author`, `page_ownerid`, `page_date`, `page_begin`, `page_expire`, `page_file`, `page_url`, `page_size`, `page_count`, `page_rating`, `page_comcount`, `page_filecount`, `page_alias`, `page_html`) VALUES
(1, 0, 0, 'news', '', '', '', '', '', '', 'Welcome !', '...', 'Congratulations, your website is up and running !\r\n\r\nNow create your account, go [url=users.php?m=auth]there[/url], then log-in with the link at the top.\r\n\r\nNote that the first user to register is automatically activated and assigned to the group "Administrators". Then, by default, all the next visitors will have to validate their account by clicking a link in an email sent by Cotonti.\r\n\r\nNext step is to go in the [url=admin.php]Administration panel[/url], tab [url=admin.php?m=config]Configuration[/url], and there tweak the settings for the system.', '', 1, 1232998830, 1232998830, 1420110000, 0, '', '', 27, '0.00', 0, 0, '', '');

CREATE TABLE `sed_pfs` (
  `pfs_id` int(11) NOT NULL auto_increment,
  `pfs_userid` int(11) NOT NULL default '0',
  `pfs_date` int(11) NOT NULL default '0',
  `pfs_file` varchar(255) collate utf8_unicode_ci NOT NULL default '',
  `pfs_extension` varchar(8) collate utf8_unicode_ci NOT NULL default '',
  `pfs_folderid` int(11) NOT NULL default '0',
  `pfs_desc` varchar(255) collate utf8_unicode_ci NOT NULL default '',
  `pfs_size` int(11) NOT NULL default '0',
  `pfs_count` int(11) NOT NULL default '0',
  PRIMARY KEY  (`pfs_id`),
  KEY `pfs_userid` (`pfs_userid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE `sed_pfs_folders` (
  `pff_id` int(11) NOT NULL auto_increment,
  `pff_parentid` INT(11),
  `pff_userid` int(11) NOT NULL default '0',
  `pff_date` int(11) NOT NULL default '0',
  `pff_updated` int(11) NOT NULL default '0',
  `pff_title` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `pff_desc` varchar(255) collate utf8_unicode_ci NOT NULL default '',
  `pff_path` VARCHAR(255),
  `pff_ispublic` tinyint(1) NOT NULL default '0',
  `pff_isgallery` tinyint(1) NOT NULL default '0',
  `pff_count` int(11) NOT NULL default '0',
  PRIMARY KEY  (`pff_id`),
  KEY `pff_userid` (`pff_userid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE `sed_plugins` (
  `pl_id` mediumint(8) NOT NULL auto_increment,
  `pl_hook` varchar(64) collate utf8_unicode_ci NOT NULL default '',
  `pl_code` varchar(24) collate utf8_unicode_ci NOT NULL default '',
  `pl_part` varchar(24) collate utf8_unicode_ci NOT NULL default '',
  `pl_title` varchar(255) collate utf8_unicode_ci NOT NULL default '',
  `pl_file` varchar(255) collate utf8_unicode_ci NOT NULL default '',
  `pl_order` tinyint(2) unsigned NOT NULL default '10',
  `pl_active` tinyint(1) unsigned NOT NULL default '1',
  PRIMARY KEY  (`pl_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=42 ;

INSERT INTO `sed_plugins` (`pl_id`, `pl_hook`, `pl_code`, `pl_part`, `pl_title`, `pl_file`, `pl_order`, `pl_active`) VALUES
(2, 'admin.home', 'cleaner', 'main', 'Cleaner', 'cleaner', 10, 1),
(3, 'standalone', 'forumstats', 'main', 'Forum statistics', 'forumstats', 10, 1),
(4, 'tools', 'massmovetopics', 'admin', 'Mass-move topics in forums', 'massmovetopics.admin', 10, 1),
(6, 'standalone', 'search', 'main', 'Search', 'search', 10, 1),
(7, 'standalone', 'statistics', 'main', 'Statistics', 'statistics', 10, 1),
(8, 'header.main', 'markitup', 'header', 'MarkItUp!', 'markitup.header', 10, 1),
(17, 'standalone', 'whosonline', 'main', 'Who''s online', 'whosonline', 10, 1),
(18, 'index.tags', 'news', 'homepage', 'News', 'news', 10, 1),
(19, 'index.tags', 'recentitems', 'recent.index', 'Recent items', 'recentitems.index', 10, 1),
(20, 'tools', 'ipsearch', 'admin', 'IP search', 'ipsearch.admin', 10, 1),
(21, 'header.main', 'search', 'header', 'Search', 'search.header', 10, 1),
(22, 'page.first', 'search', 'page', 'Search', 'search.page.first', 10, 1),
(23, 'forums.posts.first', 'search', 'forums', 'Search', 'search.forums.posts.first', 10, 1),
(24, 'index.tags', 'indexpolls', 'main', 'Indexpolls', 'indexpolls', 10, 1),
(25, 'page.tags', 'tags', 'page', 'Tags', 'tags.page', 10, 1),
(26, 'page.edit.tags', 'tags', 'page.edit.tags', 'Tags', 'tags.page.edit.tags', 10, 1),
(27, 'page.edit.update.done', 'tags', 'page.edit', 'Tags', 'tags.page.edit', 10, 1),
(28, 'page.edit.delete.done', 'tags', 'page.delete', 'Tags', 'tags.page.delete', 10, 1),
(29, 'page.add.tags', 'tags', 'page.add.tags', 'Tags', 'tags.page.add.tags', 10, 1),
(30, 'page.add.add.done', 'tags', 'page.add', 'Tags', 'tags.page.add', 10, 1),
(31, 'index.tags', 'tags', 'index', 'Tags', 'tags.index', 10, 1),
(32, 'list.tags', 'tags', 'list', 'Tags', 'tags.list', 10, 1),
(33, 'forums.topics.loop', 'tags', 'forums.topics', 'Tags', 'tags.forums.topics', 10, 1),
(34, 'forums.sections.tags', 'tags', 'forums', 'Tags', 'tags.forums', 10, 1),
(35, 'forums.newtopic.tags', 'tags', 'forums.newtopic.tags', 'Tags', 'tags.forums.newtopic.tags', 10, 1),
(36, 'forums.newtopic.newtopic.done', 'tags', 'forums.newtopic', 'Tags', 'tags.forums.newtopic', 10, 1),
(37, 'forums.editpost.tags', 'tags', 'forums.editpost.tags', 'Tags', 'tags.forums.editpost.tags', 10, 1),
(38, 'forums.editpost.update.done', 'tags', 'forums.editpost', 'Tags', 'tags.forums.editpost', 10, 1),
(39, 'forums.topics.delete.done', 'tags', 'forums.delete', 'Tags', 'tags.forums.delete', 10, 1),
(40, 'standalone', 'tags', 'search', 'Tags', 'tags', 0, 1),
(41, 'ajax', 'markitup', 'preview', 'MarkItUp!', 'markitup.ajax', 10, 1),
(42, 'header.main', 'tags', 'header', 'Tags', 'tags.header', 10, 1),
(43, 'admin.config.edit.loop', 'news', 'adminconfig', 'News', 'news.admin', 10, 1),
(44, 'standalone', 'recentitems', 'main', 'Recent items', 'recentitems', 10, 1),
(45, 'admin.page.loop', 'tags', 'admin', 'Tags', 'tags.admin', 10, 1),
(46, 'ajax', 'tags', 'ajax', 'Tags', 'tags.ajax', 10, 1);

CREATE TABLE `sed_pm` (
  `pm_id` int(11) unsigned NOT NULL auto_increment,
  `pm_state` tinyint(2) NOT NULL default '0',
  `pm_date` int(11) NOT NULL default '0',
  `pm_fromuserid` int(11) NOT NULL default '0',
  `pm_fromuser` varchar(100) collate utf8_unicode_ci NOT NULL,
  `pm_touserid` int(11) NOT NULL default '0',
  `pm_title` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `pm_text` text collate utf8_unicode_ci NOT NULL,
  `pm_html` text collate utf8_unicode_ci NOT NULL,
  PRIMARY KEY  (`pm_id`),
  KEY `pm_fromuserid` (`pm_fromuserid`),
  KEY `pm_touserid` (`pm_touserid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE `sed_polls` (
  `poll_id` mediumint(8) NOT NULL auto_increment,
  `poll_type` varchar(100) collate utf8_unicode_ci NOT NULL default 'index',
  `poll_code` varchar(16) NOT NULL default '',
  `poll_state` tinyint(1) NOT NULL default '0',
  `poll_creationdate` int(11) NOT NULL default '0',
  `poll_text` varchar(255) collate utf8_unicode_ci NOT NULL default '',
  `poll_multiple` tinyint(1) NOT NULL default '0',
  PRIMARY KEY  (`poll_id`),
  KEY `poll_creationdate` (`poll_creationdate`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE `sed_polls_options` (
  `po_id` mediumint(8) unsigned NOT NULL auto_increment,
  `po_pollid` mediumint(8) unsigned NOT NULL default '0',
  `po_text` varchar(128) collate utf8_unicode_ci NOT NULL default '',
  `po_count` mediumint(8) unsigned NOT NULL default '0',
  PRIMARY KEY  (`po_id`),
  KEY `po_pollid` (`po_pollid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE `sed_polls_voters` (
  `pv_id` mediumint(8) unsigned NOT NULL auto_increment,
  `pv_pollid` mediumint(8) NOT NULL default '0',
  `pv_userid` mediumint(8) NOT NULL default '0',
  `pv_userip` varchar(15) collate utf8_unicode_ci NOT NULL default '',
  PRIMARY KEY  (`pv_id`),
  KEY `pv_pollid` (`pv_pollid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE `sed_rated` (
  `rated_id` int(11) unsigned NOT NULL auto_increment,
  `rated_code` varchar(16) collate utf8_unicode_ci default NULL,
  `rated_userid` int(11) default NULL,
  `rated_value` tinyint(1) unsigned NOT NULL default '0',
  PRIMARY KEY  (`rated_id`),
  KEY `rated_code` (`rated_code`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE `sed_ratings` (
  `rating_id` int(11) NOT NULL auto_increment,
  `rating_code` varchar(16) collate utf8_unicode_ci NOT NULL default '',
  `rating_state` tinyint(2) NOT NULL default '0',
  `rating_average` decimal(5,2) NOT NULL default '0.00',
  `rating_creationdate` int(11) NOT NULL default '0',
  `rating_text` varchar(128) collate utf8_unicode_ci NOT NULL default '',
  PRIMARY KEY  (`rating_id`),
  KEY `rating_code` (`rating_code`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE `sed_referers` (
  `ref_url` varchar(255) collate utf8_unicode_ci NOT NULL default '',
  `ref_date` int(11) unsigned NOT NULL default '0',
  `ref_count` int(11) NOT NULL default '0',
  PRIMARY KEY  (`ref_url`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `sed_stats` (
  `stat_name` varchar(32) collate utf8_unicode_ci NOT NULL default '',
  `stat_value` int(11) NOT NULL default '0',
  PRIMARY KEY  (`stat_name`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `sed_stats` (`stat_name`, `stat_value`) VALUES
('totalpages', 0),
('totalmailsent', 0),
('totalmailpmnot', 0),
('totalpms', 0),
('totalantihammer', 0),
('textboxerprev', 0),
('version', 120);

CREATE TABLE `sed_structure` (
  `structure_id` mediumint(8) NOT NULL auto_increment,
  `structure_code` varchar(255) collate utf8_unicode_ci NOT NULL default '',
  `structure_path` varchar(16) collate utf8_unicode_ci NOT NULL default '',
  `structure_tpl` varchar(64) collate utf8_unicode_ci NOT NULL default '',
  `structure_title` varchar(100) collate utf8_unicode_ci NOT NULL,
  `structure_desc` varchar(255) collate utf8_unicode_ci NOT NULL default '',
  `structure_icon` varchar(128) collate utf8_unicode_ci NOT NULL default '',
  `structure_group` tinyint(1) NOT NULL default '0',
  `structure_order` varchar(16) collate utf8_unicode_ci NOT NULL default 'title.asc',
  `structure_pagecount` mediumint(8) NOT NULL default '0',
  `structure_comments` tinyint(1) NOT NULL default 1,
  `structure_ratings` tinyint(1) NOT NULL default 1,
  PRIMARY KEY  (`structure_id`),
  KEY `structure_path` (`structure_path`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=5 ;

INSERT INTO `sed_structure` (`structure_id`, `structure_code`, `structure_path`, `structure_tpl`, `structure_title`, `structure_desc`, `structure_icon`, `structure_group`, `structure_order`, `structure_pagecount`) VALUES
(1, 'articles', '1', '', 'Articles', '', '', 0, 'title.asc', 0),
(2, 'links', '2', '', 'Links', '', '', 0, 'title.asc', 0),
(3, 'events', '3', '', 'Events', '', '', 0, 'date.asc', 0),
(4, 'news', '4', '', 'News', '', '', 0, 'date.desc', 1);

CREATE TABLE `sed_tags` (
  `tag` varchar(255) collate utf8_unicode_ci NOT NULL,
  PRIMARY KEY  (`tag`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `sed_tag_references` (
  `tag` varchar(255) collate utf8_unicode_ci NOT NULL,
  `tag_item` int(11) NOT NULL,
  `tag_area` varchar(50) collate utf8_unicode_ci NOT NULL default 'pages',
  PRIMARY KEY  (`tag`,`tag_area`,`tag_item`),
  KEY `tag_item` (`tag_item`),
  KEY `tag_area` (`tag_area`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `sed_trash` (
  `tr_id` int(11) NOT NULL auto_increment,
  `tr_date` int(11) unsigned NOT NULL default '0',
  `tr_type` varchar(24) collate utf8_unicode_ci NOT NULL default '',
  `tr_title` varchar(128) collate utf8_unicode_ci NOT NULL default '',
  `tr_itemid` varchar(24) collate utf8_unicode_ci NOT NULL default '',
  `tr_trashedby` int(11) NOT NULL default '0',
  `tr_datas` mediumblob,
  PRIMARY KEY  (`tr_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

CREATE TABLE `sed_users` (
  `user_id` int(11) unsigned NOT NULL auto_increment,
  `user_banexpire` int(11) default '0',
  `user_name` varchar(100) collate utf8_unicode_ci NOT NULL,
  `user_password` varchar(32) collate utf8_unicode_ci NOT NULL default '',
  `user_maingrp` int(11) NOT NULL default '4',
  `user_country` char(2) collate utf8_unicode_ci NOT NULL default '',
  `user_text` text collate utf8_unicode_ci NOT NULL,
  `user_avatar` varchar(255) collate utf8_unicode_ci NOT NULL default '',
  `user_photo` varchar(255) collate utf8_unicode_ci NOT NULL default '',
  `user_signature` varchar(255) collate utf8_unicode_ci NOT NULL default '',
  `user_extra1` varchar(255) collate utf8_unicode_ci NOT NULL default '',
  `user_extra2` varchar(255) collate utf8_unicode_ci NOT NULL default '',
  `user_extra3` varchar(255) collate utf8_unicode_ci NOT NULL default '',
  `user_extra4` varchar(255) collate utf8_unicode_ci NOT NULL default '',
  `user_extra5` varchar(255) collate utf8_unicode_ci NOT NULL default '',
  `user_extra6` text collate utf8_unicode_ci,
  `user_extra7` text collate utf8_unicode_ci,
  `user_extra8` text collate utf8_unicode_ci,
  `user_extra9` text collate utf8_unicode_ci,
  `user_occupation` varchar(64) collate utf8_unicode_ci NOT NULL default '',
  `user_location` varchar(64) collate utf8_unicode_ci NOT NULL default '',
  `user_timezone` decimal(2,1) NOT NULL default '0',
  `user_birthdate` DATE NOT NULL DEFAULT '0000-00-00',
  `user_gender` char(1) collate utf8_unicode_ci NOT NULL default 'U',
  `user_irc` varchar(128) collate utf8_unicode_ci NOT NULL default '',
  `user_msn` varchar(64) collate utf8_unicode_ci NOT NULL default '',
  `user_icq` varchar(16) collate utf8_unicode_ci NOT NULL default '',
  `user_website` varchar(128) collate utf8_unicode_ci NOT NULL default '',
  `user_email` varchar(64) collate utf8_unicode_ci NOT NULL default '',
  `user_hideemail` tinyint(1) unsigned NOT NULL default '1',
  `user_pmnotify` tinyint(1) unsigned NOT NULL default '0',
  `user_newpm` tinyint(1) unsigned NOT NULL default '0',
  `user_skin` varchar(16) collate utf8_unicode_ci NOT NULL default '',
  `user_lang` varchar(16) collate utf8_unicode_ci NOT NULL default '',
  `user_regdate` int(11) NOT NULL default '0',
  `user_lastlog` int(11) NOT NULL default '0',
  `user_lastvisit` int(11) NOT NULL default '0',
  `user_lastip` varchar(16) collate utf8_unicode_ci NOT NULL default '',
  `user_logcount` int(11) unsigned NOT NULL default '0',
  `user_postcount` int(11) default '0',
  `user_sid` char(32) collate utf8_unicode_ci NOT NULL default '',
  `user_lostpass` char(32) collate utf8_unicode_ci NOT NULL default '',
  `user_auth` text collate utf8_unicode_ci,
  `user_theme` varchar(16) collate utf8_unicode_ci NOT NULL default '',
  `user_hashsalt` char(16) collate utf8_unicode_ci NOT NULL default '',
  PRIMARY KEY  (`user_id`),
  KEY `user_password` (`user_password`),
  KEY `user_regdate` (`user_regdate`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;